version: '3.8'

services:
  chat-melon:
    image: ghcr.io/ever-sync/chat-melon:latest
    ports:
      - "3000:80"
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
